# Generated by Django 3.2.8 on 2021-10-25 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_todo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
